"""
seed_demo_index.py — Seeds ChromaDB with realistic content based on the
actual vault structure discovered during scanning. Used as a fallback when
OneDrive Files On-Demand prevents reading the real files.
"""
import os
import chromadb
from sentence_transformers import SentenceTransformer

VAULT_NOTES = [
    # ── 00 Home ──────────────────────────────────────────────────────────────
    ("00 Home/Home.md", "Home", ["second-brain"], """
# Home
Welcome to my Second Brain. This vault is my personal knowledge management system built on Obsidian.
## Navigation
- [[01 Memory/Master Context]] — Who I am, my goals, preferences
- [[02 Projects/CreatorFlow]] — My main SaaS project
- [[02 Projects/Data Science Project]] — Portfolio data science work
- [[03 School/School Notes]] — All coursework
- [[04 Career/Career Ideas]] — Career planning and goals
## Daily Workflow
Each morning I review my Memory notes and update active projects.
Tags: #second-brain #home #index
"""),
    ("00 Home/Vault Health Report.md", "Vault Health Report", ["second-brain"], """
# Vault Health Report
Auto-generated report tracking the health of this Second Brain vault.
- Total notes scanned
- Broken links detected
- Orphaned notes
- Notes missing tags
This report is generated by the vault-core Rust binary.
Tags: #second-brain #meta
"""),

    # ── 01 Memory ────────────────────────────────────────────────────────────
    ("01 Memory/Master Context.md", "Master Context", ["personal", "second-brain"], """
# Master Context
## About Me
I'm Bryan Cruz, a Computer Science student and developer. I'm building a portfolio of senior-level projects.
## Current Goals
- Complete Second Brain Tools as a portfolio project (Rust + FastAPI + Next.js)
- Finish CS 146 Data Structures and Algorithms
- Launch CreatorFlow MVP
- Land a software engineering internship or entry-level role
## Strengths
- Full-stack development (Next.js, React, Python, FastAPI)
- AI/ML tooling (ChromaDB, LangChain, Claude API)
- Rust systems programming (learning)
- Problem-solving and building things from scratch
## Preferences
- I prefer dark themes, glassmorphism UI design
- I use Claude and Gemini for AI assistance
- I use Obsidian for note-taking and knowledge management
Tags: #personal #memory #context
"""),
    ("01 Memory/Coding Preferences.md", "Coding Preferences", ["coding", "personal"], """
# Coding Preferences
## Languages
- Python for AI/ML, scripting, backend APIs
- TypeScript/JavaScript for frontend (Next.js, React)
- Rust for systems programming and performance-critical code
- Some Go knowledge
## Tools & Stack
- Editor: VS Code, Cursor, Antigravity IDE
- AI: Claude (Anthropic), Gemini (Google)
- Frontend: Next.js 15+, Tailwind CSS, Glassmorphism design
- Backend: FastAPI, uvicorn, Pydantic
- Database: ChromaDB (vector), PostgreSQL
- Version Control: Git, GitHub
## Preferences
- Dark mode always
- Prefer minimal, clean APIs
- Write docstrings and comments
- Favor readability over cleverness
Tags: #coding #preferences #tools
"""),
    ("01 Memory/Commands That Worked.md", "Commands That Worked", ["coding"], """
# Commands That Worked
A log of terminal commands and tricks that solved problems.
## Rust / Cargo
- `cargo build --release` — optimized release binary
- `cargo run -- --json` — run with JSON flag
## Python / FastAPI
- `venv/bin/uvicorn main:app --reload` — start dev server
- `venv/bin/python3 rebuild_rag_index.py` — rebuild ChromaDB index
## ChromaDB
- `chroma_client.get_collection("second_brain")` — load existing collection
## macOS
- `lsof -ti:8000 | xargs kill -9` — kill process on port 8000
- `xattr -l <file>` — inspect extended attributes
Tags: #coding #commands #reference
"""),
    ("01 Memory/Imported Claude Memory Review.md", "Imported Claude Memory Review", ["personal", "second-brain"], """
# Imported Claude Memory Review
Memories imported from Claude Projects for reference.
## Key Facts Claude Knows About Me
- CS student building Second Brain Tools
- Prefer Rust for performance, Python for AI, TypeScript for frontend
- Using Obsidian + OneDrive for knowledge management
- Working on portfolio projects: Second Brain Tools, CreatorFlow, Data Science Project
- Want senior-level, production-quality code
Tags: #personal #memory #claude
"""),

    # ── 02 Projects ──────────────────────────────────────────────────────────
    ("02 Projects/CreatorFlow.md", "CreatorFlow", ["coding", "projects"], """
# CreatorFlow
## Overview
CreatorFlow is an AI-powered SaaS tool for content creators. It helps manage content pipelines, 
generate ideas, and schedule posts across platforms using AI.
## Tech Stack
- Frontend: Next.js, React, Tailwind CSS
- Backend: FastAPI, Python
- AI: Claude API for content generation
- Database: PostgreSQL, Supabase
## Status
- MVP in planning/early development
- Researching competitors: Buffer, Hootsuite, Later
## Links
- [[02 Projects/CreatorFlow - AI handoff brief]]
Tags: #coding #projects #saas #creatorflow
"""),
    ("02 Projects/CreatorFlow - AI handoff brief.md", "CreatorFlow AI Handoff Brief", ["coding", "projects"], """
# CreatorFlow — AI Handoff Brief
## Project Summary
CreatorFlow is a content creation and scheduling SaaS. This document summarizes the project 
state for AI assistant handoffs.
## Architecture
- Next.js frontend with glassmorphism design
- FastAPI backend with Claude integration
- User auth via Supabase
## Current Phase
Designing the core content pipeline feature.
## Next Steps
- Design database schema
- Build content generation endpoint
- Create post scheduling system
Tags: #coding #projects #creatorflow #ai
"""),
    ("02 Projects/Data Science Project.md", "Data Science Project", ["coding", "school"], """
# Data Science Project
## Overview
A portfolio-grade data science project for academic and career purposes.
## Links
- [[02 Projects/Data Science Project/index]]
- [[02 Projects/Data Science Project/architecture]]
- [[02 Projects/Data Science Project/project-overview]]
Tags: #coding #school #data-science
"""),
    ("02 Projects/Data Science Project/index.md", "Data Science Project Index", ["coding"], """
# Data Science Project — Index
## Sections
- [[02 Projects/Data Science Project/project-overview]] — What we're building
- [[02 Projects/Data Science Project/architecture]] — Technical design
- [[02 Projects/Data Science Project/model-notes]] — ML model notes
- [[02 Projects/Data Science Project/dashboard-notes]] — Dashboard design
- [[02 Projects/Data Science Project/next-steps]] — TODO list
Tags: #coding #data-science #index
"""),
    ("02 Projects/Data Science Project/project-overview.md", "Data Science Project Overview", ["coding"], """
# Project Overview
A machine learning project analyzing real-world data to generate insights.
## Goal
Build a complete end-to-end ML pipeline: data collection → preprocessing → modeling → visualization dashboard.
## Dataset
Using publicly available dataset with demographic and economic indicators.
## Models Evaluated
- Linear Regression (baseline)
- Random Forest
- Gradient Boosting (XGBoost)
Tags: #coding #data-science #ml
"""),
    ("02 Projects/Data Science Project/architecture.md", "Data Science Architecture", ["coding"], """
# Architecture
## Stack
- Data processing: Python, Pandas, NumPy
- ML: scikit-learn, XGBoost
- Visualization: Plotly, Dash or Next.js dashboard
- Backend: FastAPI serving model predictions
## Pipeline
1. Raw data ingestion
2. Feature engineering
3. Model training and evaluation
4. REST API for serving predictions
5. Interactive dashboard for visualization
Tags: #coding #data-science #architecture
"""),
    ("02 Projects/Data Science Project/model-notes.md", "Model Notes", ["coding"], """
# Model Notes
## Baseline: Linear Regression
- Simple, interpretable
- R² score: ~0.62
## Random Forest
- Better performance, handles non-linearity
- R² score: ~0.79
- Feature importance analysis shows top predictors
## XGBoost
- Best performer so far
- R² score: ~0.84
- Requires more hyperparameter tuning
Tags: #coding #ml #models
"""),
    ("02 Projects/Data Science Project/dashboard-notes.md", "Dashboard Notes", ["coding"], """
# Dashboard Notes
## Design
- Dark theme with data visualizations
- Interactive charts with Plotly
- Filterable by region, year, category
## Key Charts
- Feature correlation heatmap
- Prediction vs actual scatter plot
- Feature importance bar chart
- Time series trend line
Tags: #coding #dashboard #data-science
"""),
    ("02 Projects/Data Science Project/next-steps.md", "Next Steps", ["coding"], """
# Next Steps
## Immediate
- [ ] Clean and finalize dataset
- [ ] Run hyperparameter tuning on XGBoost
- [ ] Build FastAPI prediction endpoint
## Soon
- [ ] Build interactive dashboard
- [ ] Write project README
- [ ] Deploy to Render or Railway
- [ ] Add to portfolio/resume
Tags: #coding #todo #data-science
"""),
    ("02 Projects/Data Science Project/decisions.md", "Decisions", ["coding"], """
# Key Decisions
## Why XGBoost over Neural Networks?
Dataset is too small for deep learning. XGBoost gives better performance with tabular data at this size.
## Why FastAPI for serving?
Lightweight, async, automatic OpenAPI docs. Perfect for a simple ML serving endpoint.
## Why Next.js for dashboard?
Already know it well, great for interactive data viz with React components.
Tags: #coding #decisions #data-science
"""),
    ("02 Projects/Data Science Project/codebase-map.md", "Codebase Map", ["coding"], """
# Codebase Map
## Directory Structure
```
data-science-project/
├── data/          # Raw and processed datasets
├── notebooks/     # Jupyter exploration notebooks
├── src/
│   ├── preprocess.py
│   ├── train.py
│   ├── evaluate.py
│   └── serve.py   # FastAPI app
├── dashboard/     # Next.js dashboard
└── README.md
```
Tags: #coding #structure #data-science
"""),
    ("02 Projects/Data Science Project/bugs-and-fixes.md", "Bugs and Fixes", ["coding"], """
# Bugs and Fixes
## Issue: Memory error during training
- **Fix**: Reduced batch size, used chunked data loading
## Issue: Overfitting on training set
- **Fix**: Added regularization, increased cross-validation folds
## Issue: API returning 500 on edge case inputs
- **Fix**: Added input validation with Pydantic models
Tags: #coding #bugs #data-science
"""),
    ("02 Projects/Data Science Project/recruiter-explanation.md", "Recruiter Explanation", ["career", "coding"], """
# Recruiter Explanation
## How to Explain This Project to Recruiters
"I built an end-to-end machine learning pipeline that processes real-world data, trains an XGBoost model, 
serves predictions via a FastAPI REST endpoint, and visualizes results in an interactive Next.js dashboard.
The project demonstrates my ability to own a full ML product lifecycle."
## Key Talking Points
- End-to-end ML pipeline ownership
- Production-ready API with FastAPI
- Interactive visualization dashboard
- Clean, documented code
Tags: #career #projects #ml
"""),
    ("02 Projects/Data Science Project/professor-explanation.md", "Professor Explanation", ["school", "coding"], """
# Professor Explanation
## Academic Framing
This project applies supervised learning to a real-world regression problem,
demonstrating feature engineering, model selection, cross-validation, and evaluation metrics.
## Methods Used
- Train/validation/test split
- k-fold cross-validation
- RMSE, MAE, R² evaluation metrics
- Feature importance with SHAP values
Tags: #school #ml #academic
"""),
    ("02 Projects/Data Science Project/consultant-questions.md", "Consultant Questions", ["coding"], """
# Questions for Consultants/Mentors
- Is XGBoost the right choice or should I try LightGBM?
- How should I handle class imbalance if I switch to classification?
- What's the best way to monitor model drift in production?
Tags: #coding #questions #ml
"""),
    ("02 Projects/Data Science Project/prompts.md", "AI Prompts", ["coding"], """
# AI Prompts Used
## For Code Review
"Review this Python function for performance and correctness..."
## For Architecture
"Design a scalable ML serving architecture for a model with..."
## For Explanation
"Explain XGBoost feature importance in simple terms..."
Tags: #coding #ai #prompts
"""),

    # ── 03 School ────────────────────────────────────────────────────────────
    ("03 School/School Notes.md", "School Notes", ["school"], """
# School Notes
Index of all school-related notes.
## Current Courses
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Course Home]]
- CS 151 Object Oriented Programming
## Links
- [[03 School/School Notes]]
Tags: #school #index
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Course Home.md",
     "CS 146 Course Home", ["school", "coding"], """
# CS 146 — Data Structures and Algorithms
## Course Overview
Fundamental data structures and algorithms. Core CS curriculum.
## Topics Covered
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Big O Notation]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Arrays]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Linked Lists]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Stacks]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Queues]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Hash Tables]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Trees]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Binary Search Trees]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Heaps]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Graphs]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Sorting Algorithms]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Searching Algorithms]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Recursion]]
- [[03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Dynamic Programming]]
Tags: #school #cs #algorithms
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Big O Notation.md",
     "Big O Notation", ["school", "coding"], """
# Big O Notation
Big O notation describes the upper bound of algorithm time/space complexity.
## Common Complexities
- O(1) — Constant: array index access
- O(log n) — Logarithmic: binary search
- O(n) — Linear: linear search
- O(n log n) — Linearithmic: merge sort, quicksort average
- O(n²) — Quadratic: bubble sort, insertion sort worst case
- O(2ⁿ) — Exponential: recursive Fibonacci
## Rules
- Drop constants: O(2n) → O(n)
- Drop lower-order terms: O(n² + n) → O(n²)
- Worst case analysis unless specified
Tags: #school #algorithms #complexity
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Arrays.md",
     "Arrays", ["school", "coding"], """
# Arrays
A fixed-size sequential collection of elements of the same type.
## Time Complexity
- Access: O(1)
- Search: O(n)
- Insert (end): O(1) amortized
- Insert (middle): O(n)
- Delete: O(n)
## Dynamic Arrays
ArrayList / Python list — automatically resizes. Doubles capacity when full.
## Use Cases
- Random access by index
- Iteration over ordered data
- Implementing other structures (stacks, queues)
Tags: #school #data-structures #arrays
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Linked Lists.md",
     "Linked Lists", ["school", "coding"], """
# Linked Lists
Linear data structure where each node points to the next.
## Types
- Singly Linked List — each node has next pointer
- Doubly Linked List — each node has next and prev pointers
- Circular — tail points back to head
## Time Complexity
- Access: O(n)
- Search: O(n)
- Insert (head): O(1)
- Insert (tail with tail pointer): O(1)
- Delete: O(n) to find, O(1) to delete
## vs Arrays
- No random access
- Dynamic size
- Efficient head/tail insertions
Tags: #school #data-structures #linked-lists
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Stacks.md",
     "Stacks", ["school", "coding"], """
# Stacks
LIFO (Last In, First Out) data structure.
## Operations
- push(x): add to top — O(1)
- pop(): remove from top — O(1)
- peek()/top(): view top — O(1)
- isEmpty(): check if empty — O(1)
## Implementations
- Array-based (Python list)
- Linked list-based
## Use Cases
- Function call stack
- Undo operations
- Expression parsing (balanced parentheses)
- DFS graph traversal
Tags: #school #data-structures #stacks
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Queues.md",
     "Queues", ["school", "coding"], """
# Queues
FIFO (First In, First Out) data structure.
## Operations
- enqueue(x): add to back — O(1)
- dequeue(): remove from front — O(1)
- peek(): view front — O(1)
## Variants
- Deque (double-ended queue)
- Priority Queue (ordered by priority)
## Use Cases
- BFS graph traversal
- Task scheduling
- Print queues
Tags: #school #data-structures #queues
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Hash Tables.md",
     "Hash Tables", ["school", "coding"], """
# Hash Tables
Key-value store with O(1) average case operations using a hash function.
## How It Works
1. Hash function maps key to bucket index
2. Value stored at that index
3. Collision resolution: chaining or open addressing
## Time Complexity
- Insert: O(1) average, O(n) worst
- Search: O(1) average, O(n) worst
- Delete: O(1) average, O(n) worst
## Load Factor
λ = n/m (items / buckets). Should keep λ < 0.75 for performance.
## Use Cases
- Caching, memoization
- Counting frequencies
- Implementing sets
Tags: #school #data-structures #hash-tables
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Trees.md",
     "Trees", ["school", "coding"], """
# Trees
Hierarchical data structure with a root node and subtrees of children.
## Terminology
- Root: topmost node
- Leaf: node with no children
- Height: length of longest path from root to leaf
- Depth: distance from root to node
## Types
- Binary Tree: each node has at most 2 children
- Binary Search Tree (BST): left < root < right
- AVL Tree: self-balancing BST
- Heap: complete binary tree satisfying heap property
## Tree Traversals
- Inorder (L, Root, R): BST gives sorted order
- Preorder (Root, L, R): copy tree
- Postorder (L, R, Root): delete tree
- Level-order: BFS traversal
Tags: #school #data-structures #trees
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Binary Search Trees.md",
     "Binary Search Trees", ["school", "coding"], """
# Binary Search Trees (BST)
A binary tree where left subtree < node < right subtree.
## Operations
- Search: O(h) where h = height
- Insert: O(h)
- Delete: O(h)
## Balanced vs Unbalanced
- Balanced BST: h = O(log n)
- Unbalanced (worst case): h = O(n) (degenerates to linked list)
## BST Deletion Cases
1. Node is a leaf: just delete
2. Node has one child: replace with child
3. Node has two children: replace with inorder successor
Tags: #school #data-structures #bst
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Heaps.md",
     "Heaps", ["school", "coding"], """
# Heaps
Complete binary tree satisfying the heap property.
## Types
- Max-Heap: parent ≥ children (root is maximum)
- Min-Heap: parent ≤ children (root is minimum)
## Operations
- Insert: O(log n) — add at end, bubble up
- Extract-Max/Min: O(log n) — remove root, heapify down
- Peek: O(1)
- Build heap: O(n)
## Heapsort
1. Build max-heap: O(n)
2. Repeatedly extract max: O(n log n)
Total: O(n log n)
## Use Cases
- Priority queues
- Dijkstra's algorithm
- Heapsort
Tags: #school #data-structures #heaps
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Graphs.md",
     "Graphs", ["school", "coding"], """
# Graphs
Non-linear data structure with vertices (nodes) and edges.
## Types
- Directed / Undirected
- Weighted / Unweighted
- Cyclic / Acyclic (DAG = Directed Acyclic Graph)
## Representations
- Adjacency Matrix: O(V²) space, O(1) edge lookup
- Adjacency List: O(V + E) space, O(degree) edge lookup
## Traversals
- BFS (Breadth-First Search): level by level using queue
- DFS (Depth-First Search): explore fully before backtracking using stack/recursion
## Algorithms
- Dijkstra: shortest path (non-negative weights)
- Bellman-Ford: shortest path (negative weights ok)
- Kruskal/Prim: minimum spanning tree
- Topological Sort: ordering for DAGs
Tags: #school #data-structures #graphs #algorithms
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Sorting Algorithms.md",
     "Sorting Algorithms", ["school", "coding"], """
# Sorting Algorithms
## Comparison Sorts
| Algorithm      | Best     | Average  | Worst    | Space  | Stable |
|---------------|----------|----------|----------|--------|--------|
| Bubble Sort   | O(n)     | O(n²)    | O(n²)    | O(1)   | Yes    |
| Insertion Sort| O(n)     | O(n²)    | O(n²)    | O(1)   | Yes    |
| Selection Sort| O(n²)    | O(n²)    | O(n²)    | O(1)   | No     |
| Merge Sort    | O(n log n)| O(n log n)| O(n log n)| O(n) | Yes    |
| Quick Sort    | O(n log n)| O(n log n)| O(n²)   | O(log n)| No   |
| Heap Sort     | O(n log n)| O(n log n)| O(n log n)| O(1) | No    |
## Non-Comparison Sorts
- Counting Sort: O(n + k)
- Radix Sort: O(nk)
- Bucket Sort: O(n) average
Tags: #school #algorithms #sorting
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Searching Algorithms.md",
     "Searching Algorithms", ["school", "coding"], """
# Searching Algorithms
## Linear Search
- O(n) time, O(1) space
- Works on unsorted arrays
## Binary Search
- O(log n) time, O(1) space iterative
- Requires SORTED array
- Divide and conquer: compare midpoint, eliminate half
```python
def binary_search(arr, target):
    lo, hi = 0, len(arr) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        if arr[mid] == target: return mid
        elif arr[mid] < target: lo = mid + 1
        else: hi = mid - 1
    return -1
```
Tags: #school #algorithms #searching
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Recursion.md",
     "Recursion", ["school", "coding"], """
# Recursion
A function that calls itself with a smaller subproblem until a base case.
## Key Parts
1. Base case: stops recursion
2. Recursive case: calls itself with reduced input
## Call Stack
Each recursive call adds a frame to the call stack. Deep recursion → stack overflow.
## Examples
- Factorial: n! = n × (n-1)!
- Fibonacci: F(n) = F(n-1) + F(n-2)
- Binary search (recursive version)
- Tree traversals
## Tail Recursion
When the recursive call is the last operation. Some languages optimize this to iteration.
Tags: #school #algorithms #recursion
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Notes/Dynamic Programming.md",
     "Dynamic Programming", ["school", "coding"], """
# Dynamic Programming
Optimization technique: break problem into overlapping subproblems, cache results.
## When to Use
- Optimal substructure: solution to problem contains solutions to subproblems
- Overlapping subproblems: same subproblems solved multiple times
## Approaches
- Top-down (Memoization): recursion + cache
- Bottom-up (Tabulation): iterative, build from base cases
## Classic Problems
- Fibonacci (O(n) with memoization vs O(2ⁿ) naive)
- Longest Common Subsequence
- 0/1 Knapsack
- Coin Change
- Longest Increasing Subsequence
Tags: #school #algorithms #dynamic-programming
"""),
    ("03 School/Computer Science/CS 146 Data Structures and Algorithms/Study Guides/CS 146 Master Study Guide.md",
     "CS 146 Master Study Guide", ["school"], """
# CS 146 Master Study Guide
Comprehensive review of all topics for exams.
## Data Structures
- [[Arrays]] — O(1) access, O(n) search
- [[Linked Lists]] — O(1) insert at head, O(n) access
- [[Stacks]] — LIFO, O(1) push/pop
- [[Queues]] — FIFO, O(1) enqueue/dequeue
- [[Hash Tables]] — O(1) average lookup
- [[Trees]] — hierarchical, traversals
- [[Binary Search Trees]] — ordered, O(h) ops
- [[Heaps]] — complete tree, O(log n) insert/extract
- [[Graphs]] — vertices and edges, BFS/DFS
## Algorithm Strategies
- Divide and Conquer (merge sort, binary search)
- Dynamic Programming (memoization, tabulation)
- Greedy (Dijkstra, Prim)
Tags: #school #study-guide #algorithms
"""),

    # ── 04 Career ────────────────────────────────────────────────────────────
    ("04 Career/Career Ideas.md", "Career Ideas", ["personal", "career"], """
# Career Ideas
## Target Roles
- Software Engineering Intern / Entry-Level SWE
- ML Engineer / AI Engineer
- Full-Stack Developer
## Companies I'm Interested In
- Google, Anthropic, OpenAI (AI-focused)
- Startups in AI/ML space
- Mid-size tech companies
## Skills to Build
- Stronger algorithms and LeetCode practice
- System design fundamentals
- More open source contributions
- Portfolio projects (Second Brain Tools, CreatorFlow)
## Timeline
- Next 6 months: finish portfolio projects, apply for internships
Tags: #personal #career #goals
"""),

    # ── Root notes ───────────────────────────────────────────────────────────
    ("second_brain_build_roadmap.md", "Second Brain Build Roadmap", ["coding", "second-brain"], """
# Second Brain Tools — Build Roadmap
## Phase 1: ChromaDB + Vector Embeddings ✅
- Set up ChromaDB persistent store
- Index vault with sentence-transformers (all-MiniLM-L6-v2)
- RAG query pipeline
## Phase 2: Rust Parsing Engine ✅
- Rewrote vault parser in Rust using rayon (parallel processing)
- WalkDir with OneDrive-safe filtering
- JSON output mode for backend consumption
## Phase 3: Full-Stack Dashboard ✅
- FastAPI backend with health, graph, RAG query endpoints
- Next.js glassmorphism frontend
- Force-directed knowledge graph (Canvas API)
- AI Copilot chat panel with markdown rendering
## Phase 4: Future
- Real-time vault sync
- Mobile app
- Sharing / collaboration features
Tags: #coding #second-brain #roadmap
"""),
    ("CS 151 Object Oriented Programming.md", "CS 151 Object Oriented Programming", ["school", "coding"], """
# CS 151 — Object Oriented Programming
## Core OOP Concepts
- Encapsulation: bundling data and methods
- Inheritance: deriving new classes from existing ones
- Polymorphism: same interface, different implementations
- Abstraction: hiding implementation details
## Key Topics
- Classes and objects
- Constructors and destructors
- Access modifiers (public, private, protected)
- Abstract classes and interfaces
- Design patterns (Singleton, Factory, Observer)
Tags: #school #coding #oop
"""),
]


def chunk_text(text: str, chunk_size: int = 400, overlap: int = 40) -> list[str]:
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i: i + chunk_size])
        if chunk:
            chunks.append(chunk)
    return chunks


def main():
    home_dir = os.path.expanduser("~")
    db_path = os.path.join(home_dir, "IdeaProjects/second-brain-tools/chroma_db")

    print("🧠 Second Brain Demo Seeder")
    print(f"   DB: {db_path}\n")

    client = chromadb.PersistentClient(path=db_path)

    try:
        client.delete_collection("second_brain")
        print("  ↳ Cleared old collection.")
    except Exception:
        pass

    collection = client.create_collection("second_brain")

    print("Loading embedding model...")
    model = SentenceTransformer("all-MiniLM-L6-v2")
    print("  ↳ Ready.\n")

    documents, metadatas, ids = [], [], []

    for source, title, tags, content in VAULT_NOTES:
        chunks = chunk_text(content.strip())
        tags_str = ",".join(tags)
        for i, chunk in enumerate(chunks):
            documents.append(chunk)
            metadatas.append({"source": source, "title": title, "tags": tags_str})
            ids.append(f"{source}_chunk_{i}")

    print(f"Indexing {len(VAULT_NOTES)} notes → {len(documents)} chunks...")

    batch_size = 64
    total_batches = (len(documents) + batch_size - 1) // batch_size
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i: i + batch_size]
        batch_ids = ids[i: i + batch_size]
        batch_meta = metadatas[i: i + batch_size]
        embeddings = model.encode(batch_docs).tolist()
        collection.add(ids=batch_ids, embeddings=embeddings, documents=batch_docs, metadatas=batch_meta)
        print(f"  ↳ Batch {i // batch_size + 1}/{total_batches}")

    print(f"\n✅ Done! {len(VAULT_NOTES)} notes indexed into ChromaDB.")
    print("   Restart the FastAPI server and click 'Run Vault Scan' to see the graph.")


if __name__ == "__main__":
    main()
